# Generated by Django 6.0.6 on 2026-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es un empleado de la empresa', verbose_name='¿Es empleado?'),
        ),
    ]
