# Generated by Django 6.0.6 on 2026-07-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('address', models.TextField(verbose_name='Dirección Fiscal')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('currency', models.CharField(default='Bs.D', max_length=10, verbose_name='Moneda')),
                ('invoice_prefix', models.CharField(default='FAC', max_length=10, verbose_name='Prefijo de Factura')),
                ('control_number_required', models.BooleanField(default=False, help_text='Activar si la empresa usa imprenta digital autorizada', verbose_name='¿Requiere Número de Control SENIAT?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuración de la Empresa',
            },
        ),
    ]
