# Generated by Django 6.0.6 on 2026-07-21 16:33

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del archivo')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('database_type', models.CharField(default='sqlite', max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('note', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('address', models.TextField(verbose_name='Dirección Fiscal')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('invoice_prefix', models.CharField(default='FAC', max_length=10, verbose_name='Prefijo de Factura')),
                ('control_number_required', models.BooleanField(default=False, help_text='Activar si la empresa usa imprenta digital autorizada', verbose_name='¿Requiere Número de Control SENIAT?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuración de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Decimales')),
                ('is_base', models.BooleanField(default=False, help_text='Solo una moneda puede ser la base. Ej: USD, EUR, etc.', verbose_name='¿Es moneda base?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Tasa de cambio')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBackup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del archivo')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('database_type', models.CharField(default='sqlite', max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('note', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Respaldo',
                'verbose_name_plural': 'historical Respaldos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Decimales')),
                ('is_base', models.BooleanField(default=False, help_text='Solo una moneda puede ser la base. Ej: USD, EUR, etc.', verbose_name='¿Es moneda base?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Moneda',
                'verbose_name_plural': 'historical Monedas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExchangeRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Tasa de cambio')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Tasa de Cambio',
                'verbose_name_plural': 'historical Tasas de Cambio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
