# Generated by Django 6.0.6 on 2026-08-09 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si es una sucursal, selecciona la compañía matriz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.company', verbose_name='Compañía Padre'),
        ),
        migrations.AddField(
            model_name='backup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companybankaccount', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='configurati_code_d63479_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_base'], name='configurati_is_base_3ebedf_idx'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_companies', to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerate', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='configuration.currency', verbose_name='De'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='configuration.currency', verbose_name='A'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='historicalbackup',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalbackup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbackup',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalcompanybankaccount',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalcompanybankaccount',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='historicalcompanybankaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcurrency',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexchangerate',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalexchangerate',
            name='from_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='De'),
        ),
        migrations.AddField(
            model_name='historicalexchangerate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexchangerate',
            name='to_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='A'),
        ),
        migrations.AddField(
            model_name='historicalexchangerate',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='default_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentmethod', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
        migrations.AddIndex(
            model_name='companybankaccount',
            index=models.Index(fields=['company', 'is_default'], name='configurati_company_8653f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companybankaccount',
            unique_together={('company', 'bank_name', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['company', 'date'], name='configurati_company_b286ba_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency'], name='configurati_from_cu_aaee80_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['company', 'from_currency', 'to_currency', '-date'], name='configurati_company_6ab226_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('company', 'from_currency', 'to_currency', 'date', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['company', 'code'], name='configurati_company_6c3f89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('company', 'code')},
        ),
    ]
