# Generated by Django 6.0.6 on 2026-07-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Moneda principal del sistema (ej: USD, EUR)', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda base'),
        ),
    ]
