# Generated by Django 6.0.6 on 2026-08-30 16:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='note',
        ),
        migrations.RemoveField(
            model_name='historicalexchangerate',
            name='note',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exchangerate', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='effective_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 8, 30), help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(default='Manual', editable=False, max_length=100, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='effective_date',
            field=models.DateField(blank=True, default=datetime.date(2026, 8, 30), editable=False, help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='source',
            field=models.CharField(default='Manual', editable=False, max_length=100, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
    ]
