# Generated by Django 6.0.6 on 2026-07-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_company_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
    ]
