# Generated by Django 6.0.6 on 2026-08-30 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_remove_exchangerate_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia'),
        ),
    ]
