# Generated by Django 6.0.6 on 2026-07-22 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_paymentmethod_historicalpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='default_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Moneda en la que se suele realizar este pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='default_currency',
            field=models.ForeignKey(default=1, help_text='Moneda en la que se suele realizar este pago', on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda por defecto'),
            preserve_default=False,
        ),
    ]
