# Generated by Django 6.0.6 on 2026-08-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_exchangerate_effective_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tax_rate',
        ),
    ]
