# Generated by Django 6.0.6 on 2026-07-22 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_historicalpaymentmethod_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Moneda en la que se suele realizar este pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
    ]
