# Generated by Django 6.0.6 on 2026-09-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_remove_company_tax_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='configurati_company_b286ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='configurati_from_cu_aaee80_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='configurati_company_6ab226_idx',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='to_currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalExchangeRate',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
