# Generated by Django 6.0.6 on 2026-07-25 14:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_paymentmethod_default_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='requires_company_bank',
            field=models.BooleanField(default=False, help_text='Marcar si este método usa una cuenta de la empresa (transferencias, cheques)', verbose_name='¿Requiere cuenta bancaria de la empresa?'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='requires_reference',
            field=models.BooleanField(default=False, help_text='Marcar si este método requiere un número de referencia', verbose_name='¿Requiere referencia?'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_company_bank',
            field=models.BooleanField(default=False, help_text='Marcar si este método usa una cuenta de la empresa (transferencias, cheques)', verbose_name='¿Requiere cuenta bancaria de la empresa?'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_reference',
            field=models.BooleanField(default=False, help_text='Marcar si este método requiere un número de referencia', verbose_name='¿Requiere referencia?'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='default_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda por defecto'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icono'),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Banco')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Titular de la cuenta')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Cuenta Corriente'), ('SAVINGS', 'Cuenta de Ahorro')], default='CHECKING', max_length=20, verbose_name='Tipo de cuenta')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Cuenta por defecto?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cuenta Bancaria de la Empresa',
                'verbose_name_plural': 'historical Cuentas Bancarias de la Empresa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Banco')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Titular de la cuenta')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Cuenta Corriente'), ('SAVINGS', 'Cuenta de Ahorro')], default='CHECKING', max_length=20, verbose_name='Tipo de cuenta')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Cuenta por defecto?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria de la Empresa',
                'verbose_name_plural': 'Cuentas Bancarias de la Empresa',
                'ordering': ['bank_name', 'account_number'],
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
    ]
