# Generated by Django 6.0.6 on 2026-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_exchangerate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commission_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, las ventas atribuidas a un empleado generan una comisión según su tasa configurada.', verbose_name='Habilitar comisiones'),
        ),
        migrations.AddField(
            model_name='company',
            name='require_salesperson_pin',
            field=models.BooleanField(default=False, help_text='Si está activo, el sistema pedirá un PIN para asignar la venta a un empleado. Útil en peluquerías, no en supermercados.', verbose_name='Requerir PIN de vendedor al facturar'),
        ),
    ]
