# Generated by Django 6.0.6 on 2026-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_company_commission_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='require_salesperson_pin',
            field=models.BooleanField(default=False, help_text='Si está activo, el sistema pedirá un PIN para asignar la venta a un empleado.', verbose_name='Requerir PIN de vendedor al facturar'),
        ),
    ]
