# Generated by Django 6.0.6 on 2026-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_company_require_salesperson_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commission_by_service_only',
            field=models.BooleanField(default=False, help_text='Si está activo, la comisión se calcula solo sobre el subtotal de los servicios (no sobre productos). Si está desactivado, se calcula sobre el subtotal completo de la factura.', verbose_name='Comisionar solo servicios'),
        ),
    ]
