"""
Django settings for django_erp project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_0x#w-%2q1lm(-56&*fs&c$y!_qfv&cv$lt_kyf3o_ez8afo@('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.simple_history',
    'simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_erp.users',
    'django_erp.configuration',
    'django_erp.warehouse',
    'django_erp.inventory',
    'django_erp.sales',
    'django_erp.invoicing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'django_erp' / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ✅ CONFIGURACIÓN DE BASES DE DATOS
load_dotenv()

DATABASES = {
    # ✅ Base de datos PRINCIPAL (SQLite para desarrollo)
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    
    # ✅ Base de datos LOCAL (SQLite - para pruebas offline)
    'local': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_local.sqlite3',
    }
}

# ✅ ROUTER para decidir qué base de datos usar
DATABASE_ROUTERS = ['django_erp.db_routers.OfflineRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'django_erp' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SIMPLE_HISTORY_REVERT_DISABLED = False


def get_menu_items(request):
    """Genera el menú según los permisos del usuario"""
    
    user = request.user
    
    if not user.is_authenticated:
        return []
    
    navigation = []
    
    # ✅ Dashboard (siempre visible)
    
    # ✅ Almacén
    if user.has_perm('warehouse.view_product') or user.has_perm('warehouse.view_movement'):
        warehouse_items = []
        
        if user.has_perm('warehouse.view_product'):
            warehouse_items.append({
                "title": "Productos",
                "icon": "inventory_2",
                "link": "/admin/warehouse/product/",
            })
        
        if user.has_perm('warehouse.view_movement'):
            warehouse_items.append({
                "title": "Movimientos",
                "icon": "swap_horiz",
                "link": "/admin/warehouse/movement/",
            })
        
        if user.has_perm('warehouse.view_location'):
            warehouse_items.append({
                "title": "Ubicaciones",
                "icon": "location_on",
                "link": "/admin/warehouse/location/",
            })
        
        if warehouse_items:
            navigation.append({
                "title": "Almacén",
                "separator": True,
                "collapsible": True,
                "items": warehouse_items,
            })
    
    # ✅ Inventario
    if user.has_perm('inventory.view_inventory'):
        navigation.append({
            "title": "Inventario",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Inventarios",
                    "icon": "storage",
                    "link": "/admin/inventory/inventory/",
                },
                {
                    "title": "Conteos Físicos",
                    "icon": "fact_check",
                    "link": "/admin/inventory/physicalcount/",
                },
                {
                    "title": "Métodos de Valoración",
                    "icon": "calculate",
                    "link": "/admin/inventory/valuationmethod/",
                },
            ]
        })
    
    # ✅ Ventas
    if user.has_perm('sales.view_saleorder') or user.has_perm('sales.view_customer'):
        sales_items = []
        
        if user.has_perm('sales.view_customer'):
            sales_items.append({
                "title": "Clientes",
                "icon": "person",
                "link": "/admin/sales/customer/",
            })
        
        if user.has_perm('sales.view_saleorder'):
            sales_items.append({
                "title": "Órdenes de Venta",
                "icon": "receipt_long",
                "link": "/admin/sales/saleorder/",
            })
        
        if user.has_perm('sales.view_cashregister'):
            sales_items.append({
                "title": "Cierres de caja",
                "icon": "payments",
                "link": "/admin/sales/cashregister/",
            })
        
        if user.has_perm('sales.view_cashtransaction'):
            sales_items.append({
                "title": "Transacciones de Caja",
                "icon": "receipt_long",
                "link": "/admin/sales/cashtransaction/",
            })
        
        if sales_items:
            navigation.append({
                "title": "Ventas",
                "separator": True,
                "collapsible": True,
                "items": sales_items,
            })
    
    # ✅ Facturación
    if user.has_perm('invoicing.view_invoice'):
        navigation.append({
            "title": "Facturación",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Facturas",
                    "icon": "receipt",
                    "link": "/admin/invoicing/invoice/",
                },
            ]
        })
    
    # ✅ Configuración (solo administradores)
    if user.is_superuser:
        navigation.append({
            "title": "Configuración",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Empresa",
                    "icon": "business",
                    "link": "/admin/configuration/company/",
                },
                {
                    "title": "Usuarios",
                    "icon": "people",
                    "link": "/admin/users/user/",  # ← Tu URL correcta
                },
                {
                    "title": "Grupos",
                    "icon": "group",
                    "link": "/admin/auth/group/",
                },
                {
                    "title": "Monedas",
                    "icon": "attach_money",
                    "link": "/admin/configuration/currency/",
                },
                {
                    "title": "Tasas de Cambio",
                    "icon": "swap_horiz",
                    "link": "/admin/configuration/exchangerate/",
                },
                {   "title": "Métodos de Pago",
                    "icon": "payments",
                    "link": "/admin/configuration/paymentmethod/"
                },
                {
                    "title": "Respaldos",
                    "icon": "backup",
                    "link": "/admin/configuration/backup/",
                },
            ]
        })
    
    return navigation


# ✅ Configuración de UNFOLD
UNFOLD = {
    "SITE_TITLE": "Sistema ERP",
    "SITE_HEADER": "Modulos",
    "SITE_URL": "/",
    
    "MENU": {
        "ENABLED": False,
    },
    
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": get_menu_items,
    },
}