"""
Django settings for django_erp project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_0x#w-%2q1lm(-56&*fs&c$y!_qfv&cv$lt_kyf3o_ez8afo@('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_erp.users',
    'django_erp.configuration',
    'django_erp.warehouse',
    'django_erp.inventory',
    'django_erp.sales',
    'django_erp.invoicing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'django_erp' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



UNFOLD = {
    "SITE_TITLE": "Sistema ERP",
    "SITE_HEADER": "Modulos",
    "SITE_URL": "/",
    
    "MENU": {
        "ENABLED": False,
    },
    
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Almacén",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Productos",
                        "icon": "inventory_2",
                        "link": "/admin/warehouse/product/",
                    },
                    {
                        "title": "Movimientos",
                        "icon": "swap_horiz",
                        "link": "/admin/warehouse/movement/",
                    },
                    {
                        "title": "Ubicaciones",
                        "icon": "location_on",
                        "link": "/admin/warehouse/location/",
                    },
                ],
            },
            {
                "title": "Inventario",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Inventarios",
                        "icon": "storage",
                        "link": "/admin/inventory/inventory/",
                    },
                    {
                        "title": "Conteos Físicos",
                        "icon": "fact_check",
                        "link": "/admin/inventory/physicalcount/",
                    },
                    {
                        "title": "Métodos de Valoración",
                        "icon": "calculate",
                        "link": "/admin/inventory/valuationmethod/",
                    },
                ],
            },
            {
                "title": "Ventas",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Clientes",
                        "icon": "person",
                        "link": "/admin/sales/customer/",
                    },
                    {
                        "title": "Órdenes de Venta",
                        "icon": "receipt_long",
                        "link": "/admin/sales/saleorder/",
                    },
                ],
            },
             {
                "title": "Facturación",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Facturas",
                        "icon": "receipt",
                        "link": "/admin/invoicing/invoice/",
                    },
                ],
            },
            {
                "title": "Configuración",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Empresa",
                        "icon": "business",
                        "link": "/admin/configuration/company/",
                    },
                    {
                        "title": "Usuarios",
                        "icon": "people",
                        "link": "/admin/users/user/",
                    },
                    {
                        "title": "Grupos",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },

        ],
    },
}