# Generated by Django 6.0.6 on 2026-07-04 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tax_id', models.CharField(help_text='Persona Natural: V-12345678 | Empresa: J-12345678-9', max_length=20, unique=True, verbose_name='RIF / Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Órdenes de Venta',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto')),
                ('product_name', models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría jurídica'", max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('location_code', models.CharField(blank=True, help_text='Ubicación del producto en el almacén (si aplica)', max_length=50, verbose_name='Código de Ubicación')),
                ('description', models.CharField(blank=True, help_text='Usar para servicios o cuando no hay producto', max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Línea de Venta',
                'verbose_name_plural': 'Líneas de Venta',
            },
        ),
    ]
