# Generated by Django 6.0.6 on 2026-07-05 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleline',
            name='product_code',
        ),
        migrations.AddField(
            model_name='saleline',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Ubicación del producto en el almacén (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Seleccionar si es un producto físico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='description',
            field=models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='location_code',
            field=models.CharField(blank=True, help_text='Código de ubicación (si aplica)', max_length=50, verbose_name='Código de Ubicación'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='product_name',
            field=models.CharField(blank=True, help_text='Usar para servicios o cuando no hay producto seleccionado', max_length=200, verbose_name='Nombre del Producto/Servicio'),
        ),
    ]
