# Generated by Django 6.0.6 on 2026-07-11 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.cashregister', verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalcashregister',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcashregister',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsaleline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsaleline',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ubicación del producto en el almacén (si aplica)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='historicalsaleline',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccionar si es un producto físico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Ubicación del producto en el almacén (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Seleccionar si es un producto físico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleorder', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='historicalsaleline',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder', verbose_name='Orden'),
        ),
    ]
