# Generated by Django 6.0.6 on 2026-07-09 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_saleline_product_code_saleline_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dinero inicial')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ventas')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total gastos')),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total retiros')),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total esperado')),
                ('counted_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero contado')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='{"100": 5, "50": 3, "20": 10}', verbose_name='Desglose')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada'), ('APPROVED', 'Aprobada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('note', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-date', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SALE', 'Venta'), ('EXPENSE', 'Gasto'), ('WITHDRAWAL', 'Retiro'), ('DEPOSIT', 'Depósito'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.cashregister', verbose_name='Caja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción de Caja',
                'verbose_name_plural': 'Transacciones de Caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
