# Generated by Django 6.0.6 on 2026-08-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleline',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ubicación del producto en el almacén (si aplica)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Ubicación del producto en el almacén (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_line_locations', to='inventory.location', verbose_name='Ubicación'),
        ),
    ]
