# Generated by Django 6.0.6 on 2026-07-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_options_alter_saleline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(default='TEMP-0001', help_text='Persona Natural: V-12345678 | Empresa: J-12345678-9', max_length=20, unique=True, verbose_name='RIF / Cédula'),
            preserve_default=False,
        ),
    ]
