# Generated by Django 6.0.6 on 2026-07-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_paymentmethod_historicalpaymentmethod'),
        ('sales', '0003_historicalpayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Moneda en la que se realizó el pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Moneda en la que se realizó el pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda'),
        ),
    ]
