# Generated by Django 6.0.6 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_cashregister_cashtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número'),
        ),
    ]
