# Generated by Django 6.0.6 on 2026-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_historicalsaleline_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
