# Generated by Django 6.0.6 on 2026-07-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_historicalpayment_amount_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Monto en USD'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Monto en USD'),
        ),
    ]
