# Generated by Django 6.0.6 on 2026-08-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_historicalsaleinvoice_saleinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Factura a la que pertenece este pago.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleinvoice', verbose_name='Factura de Venta'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, help_text='Factura a la que pertenece este pago.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.saleinvoice', verbose_name='Factura de Venta'),
        ),
    ]
