# Generated by Django 6.0.6 on 2026-07-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_historicalpaymentmethod_requires_company_bank_and_more'),
        ('sales', '0005_alter_historicalpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pago de Venta', 'verbose_name_plural': 'historical Pagos de Ventas'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Pago de Venta', 'verbose_name_plural': 'Pagos de Ventas'},
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='customer_bank',
            field=models.CharField(blank=True, help_text='Banco desde el cual el cliente realizó el pago', max_length=200, verbose_name='Banco del cliente'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_bank',
            field=models.CharField(blank=True, help_text='Banco desde el cual el cliente realizó el pago', max_length=200, verbose_name='Banco del cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia'),
        ),
    ]
