# Generated by Django 6.0.6 on 2026-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_cashregister_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-date', '-opened_at'], 'permissions': [('can_open_register', 'Puede abrir caja'), ('can_close_register', 'Puede cerrar caja'), ('can_view_register', 'Puede ver cierres de caja')], 'verbose_name': 'Cierre de Caja', 'verbose_name_plural': 'Cierres de Caja'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('can_view_customer', 'Puede ver clientes'), ('can_edit_customer', 'Puede editar clientes'), ('can_delete_customer', 'Puede eliminar clientes')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('can_view_saleorder', 'Puede ver órdenes de venta'), ('can_edit_saleorder', 'Puede editar órdenes de venta'), ('can_delete_saleorder', 'Puede eliminar órdenes de venta'), ('can_confirm_order', 'Puede confirmar órdenes de venta'), ('can_cancel_order', 'Puede cancelar órdenes de venta'), ('can_deliver_order', 'Puede entregar órdenes de venta'), ('can_view_reports', 'Puede ver reportes de ventas')], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Órdenes de Venta'},
        ),
    ]
