# Generated by Django 6.0.6 on 2026-08-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_historicalpayment_sale_invoice_payment_sale_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.saleorder', verbose_name='Orden de Venta'),
        ),
    ]
