# Generated by Django 6.0.6 on 2026-08-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleinvoice_sale_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='sale_order',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Orden de venta a la que pertenece este pago (opcional).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder', verbose_name='Orden de Venta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale_order',
            field=models.ForeignKey(blank=True, help_text='Orden de venta a la que pertenece este pago (opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.saleorder', verbose_name='Orden de Venta'),
        ),
    ]
