# Generated by Django 6.0.6 on 2026-09-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_employee_pin'),
        ('sales', '0008_alter_historicalpayment_sale_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleinvoice',
            name='salesperson',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Empleado que realizó la venta o el servicio. Opcional: si está vacío, la factura no genera comisión.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.employee', verbose_name='Vendedor / Estilista'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='salesperson',
            field=models.ForeignKey(blank=True, help_text='Empleado que realizó la venta o el servicio. Opcional: si está vacío, la factura no genera comisión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoices', to='rrhh.employee', verbose_name='Vendedor / Estilista'),
        ),
    ]
