# Generated by Django 6.0.6 on 2026-07-23 00:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tax_id', models.CharField(help_text='Persona Natural: V-12345678 | Empresa: J-12345678-9', max_length=20, unique=True, verbose_name='RIF / Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
                'permissions': [('can_view_supplier', 'Puede ver proveedores'), ('can_edit_supplier', 'Puede editar proveedores'), ('can_delete_supplier', 'Puede eliminar proveedores')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tax_id', models.CharField(db_index=True, help_text='Persona Natural: V-12345678 | Empresa: J-12345678-9', max_length=20, verbose_name='RIF / Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Proveedor',
                'verbose_name_plural': 'historical Proveedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de entrega')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ORDERED', 'Ordenada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal (USD)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='Tasa de impuesto aplicada a la compra', max_digits=5, verbose_name='Tasa IVA (%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='IVA (USD)')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total (USD)')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-date', '-created_at'],
                'permissions': [('can_view_purchaseorder', 'Puede ver órdenes de compra'), ('can_edit_purchaseorder', 'Puede editar órdenes de compra'), ('can_delete_purchaseorder', 'Puede eliminar órdenes de compra'), ('can_confirm_order', 'Puede confirmar órdenes de compra'), ('can_receive_order', 'Puede recibir órdenes de compra'), ('can_cancel_order', 'Puede cancelar órdenes de compra')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Usar para servicios o cuando no hay producto seleccionado', max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('description', models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario (USD)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal (USD)')),
                ('location', models.ForeignKey(blank=True, help_text='Ubicación sugerida para el producto en el almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='Ubicación')),
                ('product', models.ForeignKey(blank=True, help_text='Seleccionar si es un producto físico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Producto')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Línea de Compra',
                'verbose_name_plural': 'Líneas de Compra',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Usar para servicios o cuando no hay producto seleccionado', max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('description', models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario (USD)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal (USD)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, help_text='Ubicación sugerida para el producto en el almacén', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.location', verbose_name='Ubicación')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccionar si es un producto físico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.product', verbose_name='Producto')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'historical Línea de Compra',
                'verbose_name_plural': 'historical Líneas de Compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Número')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de entrega')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ORDERED', 'Ordenada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal (USD)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='Tasa de impuesto aplicada a la compra', max_digits=5, verbose_name='Tasa IVA (%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='IVA (USD)')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total (USD)')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'historical Orden de Compra',
                'verbose_name_plural': 'historical Órdenes de Compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
