# Generated by Django 6.0.6 on 2026-08-05 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_initial'),
        ('purchasing', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ubicación sugerida para el producto en el almacén', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='company_bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta desde la cual se realiza el pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.companybankaccount', verbose_name='Cuenta de la empresa'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseinvoice', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseinvoice', verbose_name='Factura de Compra'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseinvoiceline', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinvoice', verbose_name='Factura de Compra'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseline', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Ubicación sugerida para el producto en el almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='purchase_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.purchaseline', verbose_name='Línea de Compra Original'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='purchase_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseline', verbose_name='Línea de Compra Original'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_ids',
            field=models.ManyToManyField(blank=True, to='purchasing.purchaseinvoice', verbose_name='Facturas'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasepayment', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='company_bank_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta desde la cual se realiza el pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.companybankaccount', verbose_name='Cuenta de la empresa'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.supplier', verbose_name='Proveedor'),
        ),
    ]
