# Generated by Django 6.0.6 on 2026-07-23 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='product_code',
            field=models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='product_code',
            field=models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseline',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseline',
            name='product_name',
            field=models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría'", max_length=200, verbose_name='Nombre del Producto/Servicio'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='product_name',
            field=models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría'", max_length=200, verbose_name='Nombre del Producto/Servicio'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
