# Generated by Django 6.0.6 on 2026-07-25 14:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_historicalpaymentmethod_requires_company_bank_and_more'),
        ('purchasing', '0002_historicalpurchaseline_product_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchasePayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Monto en USD')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('supplier_bank', models.CharField(blank=True, help_text='Banco al cual se realizó el pago', max_length=200, verbose_name='Banco del proveedor')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('payment_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Pago')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bank_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta desde la cual se realiza el pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.companybankaccount', verbose_name='Cuenta de la empresa')),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='Moneda')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.paymentmethod', verbose_name='Método de Pago')),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.supplier', verbose_name='Proveedor')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Pago de Compra',
                'verbose_name_plural': 'historical Pagos de Compras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Monto en USD')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('supplier_bank', models.CharField(blank=True, help_text='Banco al cual se realizó el pago', max_length=200, verbose_name='Banco del proveedor')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_bank_account', models.ForeignKey(blank=True, help_text='Cuenta desde la cual se realiza el pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.companybankaccount', verbose_name='Cuenta de la empresa')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.currency', verbose_name='Moneda')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.paymentmethod', verbose_name='Método de Pago')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchasing.purchaseorder', verbose_name='Orden de Compra')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplier', verbose_name='Proveedor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'ordering': ['-payment_date'],
            },
        ),
    ]
