# Generated by Django 6.0.6 on 2026-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado al Proveedor'), ('CONFIRMED', 'Confirmado por Proveedor'), ('RECEIVED', 'Recibido'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado al Proveedor'), ('CONFIRMED', 'Confirmado por Proveedor'), ('RECEIVED', 'Recibido'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
