# Generated by Django 6.0.6 on 2026-08-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_historicalpurchaseorder_confirmed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchasepayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalpurchasepayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Factura a la que pertenece este pago.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseinvoice', verbose_name='Factura de Compra'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, help_text='Factura a la que pertenece este pago.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchasing.purchaseinvoice', verbose_name='Factura de Compra'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
    ]
