# Generated by Django 6.0.6 on 2026-07-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_historicalpurchasepayment_purchasepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplier', verbose_name='Proveedor'),
        ),
    ]
