# Generated by Django 6.0.6 on 2026-08-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_remove_historicalpurchasepayment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
    ]
