# Generated by Django 6.0.6 on 2026-08-31 15:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0004_alter_exchangerate_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ej: VAT, ISLR, MUNICIPAL', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('tax_type', models.CharField(choices=[('SALES', 'Impuesto sobre Ventas'), ('PURCHASE', 'Impuesto sobre Compras'), ('WITHHOLDING', 'Retención'), ('OTHER', 'Otro')], default='SALES', max_length=20, verbose_name='Tipo de Impuesto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTax',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(db_index=True, help_text='Ej: VAT, ISLR, MUNICIPAL', max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('tax_type', models.CharField(choices=[('SALES', 'Impuesto sobre Ventas'), ('PURCHASE', 'Impuesto sobre Compras'), ('WITHHOLDING', 'Retención'), ('OTHER', 'Otro')], default='SALES', max_length=20, verbose_name='Tipo de Impuesto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Impuesto',
                'verbose_name_plural': 'historical Impuestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Ej: 16.00 para 16%', max_digits=5, verbose_name='Tasa (%)')),
                ('effective_date', models.DateField(help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de Vigencia')),
                ('is_default', models.BooleanField(default=False, help_text='Marca la tasa que se aplica por defecto para esta compañía e impuesto.', verbose_name='¿Tasa por defecto?')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.tax', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'historical Tasa de Impuesto',
                'verbose_name_plural': 'historical Tasas de Impuesto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Ej: 16.00 para 16%', max_digits=5, verbose_name='Tasa (%)')),
                ('effective_date', models.DateField(help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de Vigencia')),
                ('is_default', models.BooleanField(default=False, help_text='Marca la tasa que se aplica por defecto para esta compañía e impuesto.', verbose_name='¿Tasa por defecto?')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='configuration.company', verbose_name='Compañía')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='accounting.tax', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Tasa de Impuesto',
                'verbose_name_plural': 'Tasas de Impuesto',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['company', 'tax', 'effective_date'], name='accounting__company_6231b9_idx')],
                'unique_together': {('tax', 'company', 'effective_date')},
            },
        ),
    ]
