# Generated by Django 6.0.6 on 2026-08-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['code'], 'permissions': [('can_view_tax', 'Puede ver impuestos'), ('can_edit_tax', 'Puede editar impuestos'), ('can_delete_tax', 'Puede eliminar impuestos')], 'verbose_name': 'Impuesto', 'verbose_name_plural': 'Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['-effective_date'], 'permissions': [('can_view_taxrate', 'Puede ver tasas de impuesto'), ('can_edit_taxrate', 'Puede editar tasas de impuesto'), ('can_delete_taxrate', 'Puede eliminar tasas de impuesto')], 'verbose_name': 'Tasa de Impuesto', 'verbose_name_plural': 'Tasas de Impuesto'},
        ),
    ]
