# Generated by Django 6.0.6 on 2026-09-02 13:47

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_tax_options_alter_taxrate_options'),
        ('configuration', '0006_alter_exchangerate_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExchangeRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Tasa de cambio')),
                ('date', models.DateField(blank=True, editable=False, help_text='Fecha en que se registró esta tasa', verbose_name='Fecha')),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia')),
                ('source', models.CharField(default='Manual', editable=False, max_length=100, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal')),
                ('from_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='De')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.currency', verbose_name='A')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'historical Tasa de Cambio',
                'verbose_name_plural': 'historical Tasas de Cambio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Tasa de cambio')),
                ('date', models.DateField(auto_now_add=True, help_text='Fecha en que se registró esta tasa', verbose_name='Fecha')),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia')),
                ('source', models.CharField(default='Manual', editable=False, max_length=100, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exchangerate', to='configuration.company', verbose_name='Compañía/Sucursal')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='configuration.currency', verbose_name='De')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='configuration.currency', verbose_name='A')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'date'], name='accounting__company_45f460_idx'), models.Index(fields=['from_currency', 'to_currency'], name='accounting__from_cu_1859dc_idx'), models.Index(fields=['company', 'from_currency', 'to_currency', '-date'], name='accounting__company_daf61e_idx')],
                'unique_together': {('company', 'from_currency', 'to_currency', 'date', 'created_at')},
            },
        ),
    ]
