# Generated by Django 6.0.6 on 2026-09-25 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_historicalexchangerate_exchangerate'),
        ('configuration', '0009_company_commission_by_service_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='accounting__company_45f460_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='accounting__from_cu_1859dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='accounting__company_daf61e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['company', 'from_currency', 'to_currency', '-effective_date'], name='accounting__company_c37151_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['company', 'effective_date'], name='accounting__company_69b420_idx'),
        ),
    ]
