# Generated by Django 6.0.6 on 2026-09-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active_employee',
        ),
    ]
