# Generated by Django 6.0.6 on 2026-09-10 19:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_remove_employee_is_active_employee'),
        ('sales', '0008_alter_historicalpayment_sale_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión sobre el subtotal de las ventas', max_digits=5, verbose_name='Comisión (%)'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base (subtotal sin IVA)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje aplicado (%)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto comisión')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='rrhh.employee', verbose_name='Empleado')),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.saleinvoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-created_at'],
                'permissions': [('can_view_commission', 'Puede ver comisiones'), ('can_pay_commission', 'Puede marcar comisiones como pagadas')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'sale_invoice'), name='unique_commission_per_invoice_employee')],
            },
        ),
    ]
