# Generated by Django 6.0.6 on 2026-09-10 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_employee_commission_rate_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Porcentaje de comisión sobre el subtotal de las ventas', max_digits=5, verbose_name='Comisión (%)'),
        ),
    ]
