# Generated by Django 6.0.6 on 2026-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_employee_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN numérico de 4 a 6 dígitos para identificar al empleado al momento de facturar. Debe ser único entre empleados activos.', max_length=6, null=True, unique=True, verbose_name='PIN de acceso'),
        ),
    ]
