# Generated by Django 6.0.6 on 2026-09-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_company_commission_by_service_only'),
        ('rrhh', '0005_employee_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='configuration.company', verbose_name='Compañía'),
        ),
    ]
