# Generated by Django 6.0.6 on 2026-09-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_alter_commission_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_commission', 'Puede ver comisiones'), ('can_pay_commission', 'Puede marcar comisiones como pagadas'), ('can_view_all_commissions', 'Puede ver todas las comisiones de la empresa')], 'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
    ]
