# Generated by Django 6.0.6 on 2026-07-04 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número Interno')),
                ('control_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control SENIAT')),
                ('issuer_rif', models.CharField(max_length=20, verbose_name='RIF Emisor')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Nombre Emisor')),
                ('issuer_address', models.TextField(verbose_name='Dirección Emisor')),
                ('customer_data', models.JSONField(blank=True, default=dict, help_text="Ejemplo: {'name': 'Juan Pérez', 'rif': 'V-12345678', 'address': 'Calle Falsa 123'}", verbose_name='Datos del Cliente')),
                ('sale_order_number', models.CharField(blank=True, help_text='Referencia a la orden de venta (si aplica)', max_length=50, null=True, verbose_name='Número de Orden de Venta')),
                ('concept', models.CharField(blank=True, help_text='Usar si no hay orden de venta', max_length=200, verbose_name='Concepto')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(blank=True, default=dict, help_text="Ejemplo: {'name': 'Laptop HP', 'code': 'LAP-001', 'unit_price': 1200}", verbose_name='Datos del Producto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
            },
        ),
    ]
