# Generated by Django 6.0.6 on 2026-07-21 16:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoiceLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID Universal')),
                ('product_code', models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto')),
                ('product_name', models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría jurídica'", max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('description', models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Línea de Factura',
                'verbose_name_plural': 'historical Líneas de Factura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Universal')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('SYNCING', 'Sincronizando...'), ('SYNCED', 'Sincronizada'), ('FAILED', 'Error en sincronización')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de sincronización')),
                ('created_at_local', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado localmente')),
                ('device_id', models.CharField(blank=True, help_text='Identificador del equipo que creó la factura', max_length=100, null=True, verbose_name='Dispositivo de creación')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado el')),
                ('sync_attempts', models.IntegerField(default=0, verbose_name='Intentos de sincronización')),
                ('sync_error', models.TextField(blank=True, verbose_name='Error de sincronización')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número Interno')),
                ('control_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control SENIAT')),
                ('issuer_rif', models.CharField(max_length=20, verbose_name='RIF Emisor')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Nombre Emisor')),
                ('issuer_address', models.TextField(verbose_name='Dirección Emisor')),
                ('customer_name', models.CharField(blank=True, help_text='Ejemplo: Juan Pérez', max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_rif', models.CharField(blank=True, help_text='Ejemplo: V-12345678 o J-12345678-9', max_length=20, verbose_name='RIF / Cédula del Cliente')),
                ('customer_address', models.TextField(blank=True, help_text='Ejemplo: Calle Falsa 123, Ciudad', verbose_name='Dirección del Cliente')),
                ('sale_order_number', models.CharField(blank=True, help_text='Referencia a la orden de venta (si aplica)', max_length=50, null=True, verbose_name='Número de Orden de Venta')),
                ('concept', models.CharField(blank=True, help_text='Usar si no hay líneas específicas', max_length=200, verbose_name='Concepto')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-date', '-created_at'],
                'permissions': [('can_view_invoice', 'Puede ver facturas'), ('can_edit_invoice', 'Puede editar facturas'), ('can_delete_invoice', 'Puede eliminar facturas'), ('can_issue_invoice', 'Puede emitir facturas'), ('can_pay_invoice', 'Puede pagar facturas'), ('can_cancel_invoice', 'Puede anular facturas')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Universal')),
                ('product_code', models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto')),
                ('product_name', models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría jurídica'", max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('description', models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
                'permissions': [('can_view_invoiceline', 'Puede ver líneas de factura'), ('can_edit_invoiceline', 'Puede editar líneas de factura')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID Universal')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('SYNCING', 'Sincronizando...'), ('SYNCED', 'Sincronizada'), ('FAILED', 'Error en sincronización')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de sincronización')),
                ('created_at_local', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Creado localmente')),
                ('device_id', models.CharField(blank=True, help_text='Identificador del equipo que creó la factura', max_length=100, null=True, verbose_name='Dispositivo de creación')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado el')),
                ('sync_attempts', models.IntegerField(default=0, verbose_name='Intentos de sincronización')),
                ('sync_error', models.TextField(blank=True, verbose_name='Error de sincronización')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Número Interno')),
                ('control_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control SENIAT')),
                ('issuer_rif', models.CharField(max_length=20, verbose_name='RIF Emisor')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Nombre Emisor')),
                ('issuer_address', models.TextField(verbose_name='Dirección Emisor')),
                ('customer_name', models.CharField(blank=True, help_text='Ejemplo: Juan Pérez', max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_rif', models.CharField(blank=True, help_text='Ejemplo: V-12345678 o J-12345678-9', max_length=20, verbose_name='RIF / Cédula del Cliente')),
                ('customer_address', models.TextField(blank=True, help_text='Ejemplo: Calle Falsa 123, Ciudad', verbose_name='Dirección del Cliente')),
                ('sale_order_number', models.CharField(blank=True, help_text='Referencia a la orden de venta (si aplica)', max_length=50, null=True, verbose_name='Número de Orden de Venta')),
                ('concept', models.CharField(blank=True, help_text='Usar si no hay líneas específicas', max_length=200, verbose_name='Concepto')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'historical Factura',
                'verbose_name_plural': 'historical Facturas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
