# Generated by Django 6.0.6 on 2026-07-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='product_data',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product_code',
            field=models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product_name',
            field=models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría jurídica'", max_length=200, verbose_name='Nombre del Producto/Servicio'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='concept',
            field=models.CharField(blank=True, help_text='Usar si no hay líneas específicas', max_length=200, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_data',
            field=models.JSONField(blank=True, default=dict, help_text='{"name": "Juan Pérez", "rif": "V-12345678", "address": "Calle Falsa 123"}', verbose_name='Datos del Cliente'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción'),
        ),
    ]
