# Generated by Django 6.0.6 on 2026-07-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_remove_invoiceline_product_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_data',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Ejemplo: Calle Falsa 123, Ciudad', verbose_name='Dirección del Cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Ejemplo: Juan Pérez', max_length=200, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_rif',
            field=models.CharField(blank=True, help_text='Ejemplo: V-12345678 o J-12345678-9', max_length=20, verbose_name='RIF / Cédula del Cliente'),
        ),
    ]
