# Generated by Django 6.0.6 on 2026-07-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_historicalinvoiceline_product_invoiceline_product'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='Cliente'),
        ),
    ]
