# Generated by Django 6.0.6 on 2026-07-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='payment_summary',
            field=models.JSONField(blank=True, default=dict, help_text='{"CASH": 300, "CREDIT_CARD": 200}', verbose_name='Resumen de Pagos'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_summary',
            field=models.JSONField(blank=True, default=dict, help_text='{"CASH": 300, "CREDIT_CARD": 200}', verbose_name='Resumen de Pagos'),
        ),
    ]
