# Generated by Django 6.0.6 on 2026-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_remove_invoice_customer_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('can_view_invoice', 'Puede ver facturas'), ('can_edit_invoice', 'Puede editar facturas'), ('can_delete_invoice', 'Puede eliminar facturas'), ('can_issue_invoice', 'Puede emitir facturas'), ('can_pay_invoice', 'Puede pagar facturas'), ('can_cancel_invoice', 'Puede anular facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'permissions': [('can_view_invoiceline', 'Puede ver líneas de factura'), ('can_edit_invoiceline', 'Puede editar líneas de factura')], 'verbose_name': 'Línea de Factura', 'verbose_name_plural': 'Líneas de Factura'},
        ),
    ]
