# Generated by Django 6.0.6 on 2026-07-10 21:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('invoicing', '0004_alter_invoice_options_alter_invoiceline_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Número Interno')),
                ('control_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control SENIAT')),
                ('issuer_rif', models.CharField(max_length=20, verbose_name='RIF Emisor')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Nombre Emisor')),
                ('issuer_address', models.TextField(verbose_name='Dirección Emisor')),
                ('customer_name', models.CharField(blank=True, help_text='Ejemplo: Juan Pérez', max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_rif', models.CharField(blank=True, help_text='Ejemplo: V-12345678 o J-12345678-9', max_length=20, verbose_name='RIF / Cédula del Cliente')),
                ('customer_address', models.TextField(blank=True, help_text='Ejemplo: Calle Falsa 123, Ciudad', verbose_name='Dirección del Cliente')),
                ('sale_order_number', models.CharField(blank=True, help_text='Referencia a la orden de venta (si aplica)', max_length=50, null=True, verbose_name='Número de Orden de Venta')),
                ('concept', models.CharField(blank=True, help_text='Usar si no hay líneas específicas', max_length=200, verbose_name='Concepto')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Factura',
                'verbose_name_plural': 'historical Facturas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvoiceLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, help_text='Código del producto (si aplica)', max_length=50, verbose_name='Código de Producto')),
                ('product_name', models.CharField(blank=True, help_text="Ejemplo: 'Laptop HP 15.6' o 'Consultoría jurídica'", max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('description', models.CharField(blank=True, help_text='Detalle adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoicing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'historical Línea de Factura',
                'verbose_name_plural': 'historical Líneas de Factura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
