# Generated by Django 6.0.6 on 2026-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_historicalinvoice_change_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='change_summary',
            field=models.JSONField(blank=True, default=dict, help_text='{"USD": 20, "BS": 500}', verbose_name='Vuelto por Moneda'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='change_summary',
            field=models.JSONField(blank=True, default=dict, help_text='{"USD": 20, "BS": 500}', verbose_name='Vuelto por Moneda'),
        ),
    ]
