# Generated by Django 6.0.6 on 2026-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit', models.CharField(choices=[('UNIT', 'Unit'), ('KG', 'Kilogram'), ('L', 'Liter'), ('M', 'Meter'), ('BOX', 'Box'), ('PACK', 'Pack')], default='UNIT', max_length=10, verbose_name='Unit of measure')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Purchase price')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sale price')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Minimum stock')),
                ('max_stock', models.IntegerField(default=0, verbose_name='Maximum stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
