# Generated by Django 6.0.6 on 2026-08-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('code', 'company')},
        ),
    ]
