# Generated by Django 6.0.6 on 2026-06-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_product_options_remove_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='movement',
            name='total',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dimensiones (LxAxA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PURCHASE', 'Compra'), ('SALE', 'Venta')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('TRANSFER', 'Traslado'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UNIT', 'Unidad'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('M', 'Metro')], default='UNIT', max_length=10, verbose_name='Unidad'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='Ubicación padre')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='warehouse.location', verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='movement',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='warehouse.location', verbose_name='Hasta'),
        ),
    ]
