# Generated by Django 6.0.6 on 2026-07-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Marcar si es un servicio (no requiere control de stock)', verbose_name='¿Es servicio?'),
        ),
    ]
