# Generated by Django 6.0.6 on 2026-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_product_is_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['code'], 'permissions': [('can_view_location', 'Puede ver ubicaciones'), ('can_edit_location', 'Puede editar ubicaciones')], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_movement', 'Puede ver movimientos'), ('can_edit_movement', 'Puede editar movimientos'), ('can_delete_movement', 'Puede eliminar movimientos')], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_view_product', 'Puede ver productos'), ('can_edit_product', 'Puede editar productos'), ('can_delete_product', 'Puede eliminar productos'), ('can_import_products', 'Puede importar productos'), ('can_export_products', 'Puede exportar productos')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
