# Generated by Django 6.0.6 on 2026-06-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_movement_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='movement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra para entradas, precio de venta para salidas', max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
