# Generated by Django 6.0.6 on 2026-06-29 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0003_alter_movement_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(auto_now_add=True, verbose_name='Fecha de conteo')),
                ('counted_quantity', models.IntegerField(verbose_name='Cantidad contada')),
                ('system_quantity', models.IntegerField(verbose_name='Cantidad en sistema')),
                ('difference', models.IntegerField(editable=False, verbose_name='Diferencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='warehouse.location', verbose_name='Ubicación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='warehouse.product', verbose_name='Producto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='ValuationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FIFO', 'FIFO (First In First Out)'), ('LIFO', 'LIFO (Last In First Out)'), ('AVERAGE', 'Costo Promedio'), ('STANDARD', 'Costo Estándar')], default='AVERAGE', max_length=10, verbose_name='Método')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo estándar')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_method', to='warehouse.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Método de Valoración',
                'verbose_name_plural': 'Métodos de Valoración',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo promedio')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouse.location', verbose_name='Ubicación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouse.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
