# Generated by Django 6.0.6 on 2026-07-21 16:33

import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo promedio')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Inventario',
                'verbose_name_plural': 'historical Inventarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPhysicalCount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID Universal')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('SYNCING', 'Sincronizando...'), ('SYNCED', 'Sincronizada'), ('FAILED', 'Error en sincronización')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de sincronización')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispositivo de creación')),
                ('count_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de conteo')),
                ('counted_quantity', models.IntegerField(verbose_name='Cantidad contada')),
                ('system_quantity', models.IntegerField(verbose_name='Cantidad en sistema')),
                ('difference', models.IntegerField(editable=False, verbose_name='Diferencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Conteo Físico',
                'verbose_name_plural': 'historical Conteos Físicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalValuationMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('method', models.CharField(choices=[('FIFO', 'FIFO (First In First Out)'), ('LIFO', 'LIFO (Last In First Out)'), ('AVERAGE', 'Costo Promedio'), ('STANDARD', 'Costo Estándar')], default='AVERAGE', max_length=10, verbose_name='Método')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo estándar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Método de Valoración',
                'verbose_name_plural': 'historical Métodos de Valoración',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo promedio')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'permissions': [('can_view_inventory', 'Puede ver inventarios'), ('can_edit_inventory', 'Puede editar inventarios')],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Universal')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('SYNCING', 'Sincronizando...'), ('SYNCED', 'Sincronizada'), ('FAILED', 'Error en sincronización')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de sincronización')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispositivo de creación')),
                ('count_date', models.DateField(auto_now_add=True, verbose_name='Fecha de conteo')),
                ('counted_quantity', models.IntegerField(verbose_name='Cantidad contada')),
                ('system_quantity', models.IntegerField(verbose_name='Cantidad en sistema')),
                ('difference', models.IntegerField(editable=False, verbose_name='Diferencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-count_date'],
                'permissions': [('can_view_physicalcount', 'Puede ver conteos físicos'), ('can_create_physicalcount', 'Puede crear conteos físicos'), ('can_confirm_physicalcount', 'Puede confirmar conteos físicos')],
            },
        ),
        migrations.CreateModel(
            name='ValuationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FIFO', 'FIFO (First In First Out)'), ('LIFO', 'LIFO (Last In First Out)'), ('AVERAGE', 'Costo Promedio'), ('STANDARD', 'Costo Estándar')], default='AVERAGE', max_length=10, verbose_name='Método')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo estándar')),
            ],
            options={
                'verbose_name': 'Método de Valoración',
                'verbose_name_plural': 'Métodos de Valoración',
                'permissions': [('can_view_valuationmethod', 'Puede ver métodos de valoración'), ('can_edit_valuationmethod', 'Puede editar métodos de valoración')],
            },
        ),
    ]
