# Generated by Django 6.0.6 on 2026-08-09 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvaluationmethod',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='historicalvaluationmethod',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Ubicación padre'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='location_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='location_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Hasta'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Ubicación padre'),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='movement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='movement',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.location', verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='movement',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.location', verbose_name='Hasta'),
        ),
        migrations.AddField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicalcount', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalvaluationmethod',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='valuationmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuationmethod', to='configuration.company', verbose_name='Compañía/Sucursal'),
        ),
        migrations.AddField(
            model_name='valuationmethod',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_method', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('code', 'company')},
        ),
        migrations.AddIndex(
            model_name='physicalcount',
            index=models.Index(fields=['uuid'], name='inventory_p_uuid_e49f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalcount',
            index=models.Index(fields=['sync_status'], name='inventory_p_sync_st_c3aa58_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['uuid'], name='inventory_m_uuid_388f70_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['sync_status'], name='inventory_m_sync_st_223a73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location', 'company')},
        ),
    ]
