# Generated by Django 6.0.6 on 2026-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('can_view_inventory', 'Puede ver inventarios'), ('can_edit_inventory', 'Puede editar inventarios')], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='physicalcount',
            options={'ordering': ['-count_date'], 'permissions': [('can_view_physicalcount', 'Puede ver conteos físicos'), ('can_create_physicalcount', 'Puede crear conteos físicos'), ('can_confirm_physicalcount', 'Puede confirmar conteos físicos')], 'verbose_name': 'Conteo Físico', 'verbose_name_plural': 'Conteos Físicos'},
        ),
        migrations.AlterModelOptions(
            name='valuationmethod',
            options={'permissions': [('can_view_valuationmethod', 'Puede ver métodos de valoración'), ('can_edit_valuationmethod', 'Puede editar métodos de valoración')], 'verbose_name': 'Método de Valoración', 'verbose_name_plural': 'Métodos de Valoración'},
        ),
    ]
