# Generated by Django 6.0.6 on 2026-08-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
        ('inventory', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location', 'company')},
        ),
    ]
