# Generated by Django 6.0.6 on 2026-08-09 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_deliverynote_deliverynoteline_historicaldeliverynote_and_more'),
        ('purchasing', '0003_historicalpurchaseorder_confirmed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Orden de compra que originó esta nota (si aplica).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='receiptnote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Orden de compra que originó esta nota (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_notes', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
    ]
