# Generated by Django 6.0.6 on 2026-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalreceiptnote_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
    ]
