# Generated by Django 6.0.6 on 2026-08-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_deliverynote_confirmed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuationmethod',
            name='company',
        ),
        migrations.RemoveField(
            model_name='valuationmethod',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='average_cost',
        ),
        migrations.DeleteModel(
            name='HistoricalValuationMethod',
        ),
        migrations.DeleteModel(
            name='ValuationMethod',
        ),
    ]
