# Generated by Django 6.0.6 on 2026-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_valuationmethod_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra para referencia. El costo real se calcula desde los movimientos.', max_digits=10, null=True, verbose_name='Precio de Compra (USD)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al que se vende al cliente', max_digits=10, verbose_name='Precio de Venta (USD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra para referencia. El costo real se calcula desde los movimientos.', max_digits=10, null=True, verbose_name='Precio de Compra (USD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al que se vende al cliente', max_digits=10, verbose_name='Precio de Venta (USD)'),
        ),
    ]
