# Generated by Django 6.0.6 on 2026-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_historicalproduct_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra para referencia. El costo real se calcula desde los movimientos.', max_digits=10, verbose_name='Precio de Compra (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra para referencia. El costo real se calcula desde los movimientos.', max_digits=10, verbose_name='Precio de Compra (USD)'),
        ),
    ]
