# Generated by Django 6.0.6 on 2026-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_historicalproduct_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalphysicalcount',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ajuste de Inventario', 'verbose_name_plural': 'historical Ajustes de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='physicalcount',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_physicalcount', 'Puede ver ajustes de inventario'), ('can_create_physicalcount', 'Puede crear ajustes de inventario')], 'verbose_name': 'Ajuste de Inventario', 'verbose_name_plural': 'Ajustes de Inventario'},
        ),
        migrations.RemoveIndex(
            model_name='physicalcount',
            name='inventory_p_uuid_e49f5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='physicalcount',
            name='inventory_p_sync_st_c3aa58_idx',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='count_date',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='counted_quantity',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='system_quantity',
        ),
        migrations.RemoveField(
            model_name='historicalphysicalcount',
            name='uuid',
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='adjustment_quantity',
            field=models.IntegerField(default=0, help_text='Nueva cantidad que debe quedar en el sistema', verbose_name='Cantidad a ajustar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalphysicalcount',
            name='available_quantity',
            field=models.IntegerField(default=0, help_text='Cantidad actual en el sistema (solo lectura)', verbose_name='Cantidad disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='adjustment_quantity',
            field=models.IntegerField(default=0, help_text='Nueva cantidad que debe quedar en el sistema', verbose_name='Cantidad a ajustar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='available_quantity',
            field=models.IntegerField(default=0, help_text='Cantidad actual en el sistema (solo lectura)', verbose_name='Cantidad disponible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalphysicalcount',
            name='difference',
            field=models.IntegerField(editable=False, help_text='Ajuste = Cantidad ajustada - Cantidad disponible', verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='physicalcount',
            name='difference',
            field=models.IntegerField(editable=False, help_text='Ajuste = Cantidad ajustada - Cantidad disponible', verbose_name='Diferencia'),
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='count_date',
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='counted_quantity',
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='system_quantity',
        ),
        migrations.RemoveField(
            model_name='physicalcount',
            name='uuid',
        ),
    ]
