# Generated by Django 6.0.6 on 2026-09-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_historicalphysicalcount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynoteline',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='inventory.deliverynote', verbose_name='Nota de Entrega'),
        ),
        migrations.AlterField(
            model_name='receiptnoteline',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='inventory.receiptnote', verbose_name='Nota de Recibo'),
        ),
    ]
