# Generated by Django 6.0.6 on 2026-09-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_deliverynoteline_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmovement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalmovement',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmovement',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='historicalmovement',
            name='location_to',
        ),
        migrations.RemoveField(
            model_name='historicalmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalmovement',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalInventory',
        ),
        migrations.DeleteModel(
            name='HistoricalMovement',
        ),
    ]
